name: food_delivery
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_fonts: ^2.1.0
  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/
